### ISSUE TITLE
Recurring Donations Not Respecting Forecast Months Setting When Next Donation Date Changed

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#3500] opened 2018-07-19 14:30 UTC
When the Next Donation Date of an Open Ended Recurring Donation occurs after the Date Established, pledged Opportunities are created with Close Dates from that day forward, while using the Opportunity Forecast Months setting in NPSP Settings to determine the total number of Opportunities to create. If, however, the Next Donation Date is changed, the Opportunity Forecast Months setting is no longer respected and you may have pledged Opportunities well past your forecast period.

**_Scenario 1 (the control):_** When you create an RD with a Date Established of 1/1/2017, but want pledged Opportunities to be generated only for future dates, you would set your Next Donation Date to 8/1/2018, for example. The total number of Opportunities would be determined by your Opportunity Forecast Months setting in NPSP Settings.

**_Scenario 2 (the bug):_** If you create an RD with a Date Established of 1/1/2017 but leave the Next Donation Date blank,  pledged Opportunities are generated from 1/1/2017 through the number of forecast months you've created after today's date. This is fine, but if you then change the Next Donation Date to a date in the future to presumably remove those past pledged Opportunities, it just changes Close Dates on those same pledged Opportunities and does not take the Opportunity Forecast Months setting into consideration (so you may have 30 pledged Opportunities instead of 11 in my case).

**Steps to Repeat:**

1. Verify that Opportunity Forecast Months setting = 12 in NPSP Settings → Recurring Donations → Recurring Donations.
2. Create a Contact record.

3. (The Control — works as expected)
    A. Create a Recurring Donation (Contact = your Contact, Amount = 10, Open Ended Status = Open, Date Established = 1/1/2017, Next Donation Date = 8/1/2018, Installment Period = Monthly)
    B. Verify that 12 months' worth of pledged Opportunities were created (based on today's date, 7/19/18, it generated 11 Opportunities.)

4. (The Bug)
    A.  Create a Recurring Donation (Contact = your Contact, Amount = 5, Open Ended Status = Open, Date Established = 1/1/2017, Installment Period = Monthly). Don't set a Next Donation Date!
    B. Verify that Pledged Opportunities were created with Close Dates starting 1/1/2017 through today, plus the number of forecast months. In my org, there are 30 pledged Opportunities, ranging from 1/1/2017 - 6/1/2019.
    C. Change the Next Donation Date on the Recurring Donation to 8/1/2018. This will change the pledged Opportunities so that the first Close Date is now 8/1/2018 (This is expected behavior).
    D. However, the Opportunity Forecast Months setting is not respected. So, you have 30 Pledged Opportunities starting at 8/1/2018 and going through 1/1/2021. (Not expected behavior).

**Comment by jesslopez-sf** [comment] 2018-07-19 14:31
**lurch: add

**Comment by LurchTheButler** [comment] 2018-07-19 14:35
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYC4BAAX" target="_blank">W-026417</a>

**Comment by blueiguana** [comment] 2018-07-25 08:08
Thanks for this - it's exactly what we were experiencing when trying to change the Next Donation Date. Until this is fixed, what is the workaround?

**Comment by judisohn** [comment] 2018-07-25 10:43
@jesslopez-sf could you update the issue with the workaround to assist @blueiguana? Thanks!

**Comment by annacrotty** [comment] 2018-07-25 23:56
Support has suggested that something I'm seeing may be related to this and so I'm commenting. 

I have forecast months set for 12.  Today is July 25th and all of the yearly recurring donations that have been processed so far in July have zero open pledges.  Monthly recurring donations that have been processed so far in July have 11 open pledges. Based on past experience, I believe all those open pledges will be created on August 1st or 2nd.  

Is this expected behavior?  Support hasn't been clear on that.  One downside is that our open pledge metric fluctuates wildly depending on how late in the month it is, especially during months when we have a lot of yearly donations.  (It makes it look like we're losing and gaining pledges when we're not.)

To be clear:  the behavior I'm describing doesn't involve any dates changing.  The behavior surprised us when we realized it was the reason our metrics are so wonky, but at this point we're just trying to verify that we're seeing expected behavior and don't have something additional to troubleshoot.

**Comment by blueiguana** [comment] 2018-07-26 13:44
Yes, Anna, I think you’ve described how it works correctly. Our situation was to specify the Next Donation Data incorrectly or not at all, whereupon NPSP created a lot of historical pledged opportunities. Updating the Next Donation Date then just shifted the dates of those pledged opportunities while keeping the same number.

My observation of your KPI  of counting pledged opportunities is that you shouldn’t! It will lead to the fluctuations you describe, unless you always count from the 1st of the next month each time. Also, maybe you should count Contacts with pledged opportunities rather than the pledged opportunities themselves.

Jonathan

**Comment by jesslopez-sf** [comment] 2018-07-26 21:50
@blueiguana 
Hi Jonathan,

As a workaround, I would suggest a formula field to identify which Opportunities are now outside of your forecast period.  Then create a report (or use the data loader) and export Opportunities where this formula field is true. Then either delete them or set them to a Closed Lost stage (depending on data storage  / etc.)

**Steps:**

1. Back up all of your Opportunities first.
2. Create a formula field
    1. Label = Beyond Forecast Period
    2. Return Type = Checkbox
    3. Formula = 
`IF( ISPICKVAL(npe03__Recurring_Donation__r.npe03__Open_Ended_Status__c, 'Open') && CloseDate > ADDMONTHS(TODAY(), $Setup.npe03__Recurring_Donations_Settings__c.npe03__Opportunity_Forecast_Months__c), true, false)`
3. Create a report of all Opportunities where Beyond Forecast Period = true. Make sure to grab the Id.
4. Export
5. Assuming the formula field is accurate to your org **, you can then delete (or change the Stage to a closed lost stage) using the Data Loader or your tool of choice.


** You may need to tweak it slightly based on customizations in your org, but it should be able to identify these Opportunities fairly accurately and quickly.

And finally, if you want to prevent this scenario from occurring in the future, you can create a Validation Rule on Recurring Donations that fires when the Date Established is before a date that you choose and the Next Donation Date is blank. (Again, this will be dependent on your customizations and processes). 

Hope this helps!

**Comment by blueiguana** [comment] 2018-07-27 13:50
Thanks Jess. Our main issue though is with historical, pledged opportunities.

**Comment by mpusto** [comment] 2020-06-03 17:26
We are closing this issue because we will not be updating the old Recurring Donations functionality. We will be making all updates to our new Recurring Donations functionality. We recommend that customers evaluate the new features and upgrade when it makes sense for their organization. https://powerofus.force.com/s/article/NPSP-Enhanced-RD-Upgrade-Guide

**Closed by mpusto** 2020-06-03 17:26 UTC
