### ISSUE TITLE
Changing the Contact owner results in an error when the Primary Contact is not related to the Account

### ISSUE THREAD

**Issue by jjbennett** [SalesforceFoundation/NPSP#2631] opened 2017-07-10 15:25 UTC
Steps to Replicate:
1. Create 2 Contacts at 2 separate Households
2. Set Contact B as the Primary Contact at Contact A's Household
3. Change Contact A's Owner

The following error will display:
"npsp.TDTM_Contact: execution of AfterUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id 001B000000UPdHuIAL; first error: INVALID_CROSS_REFERENCE_KEY, Owner ID: owner cannot be blank: [OwnerId] (npsp)"

Suspect code in "ACCT_IndividualAccounts_TDTM" - "updateOwner" method.

**Comment by jjbennett** [comment] 2017-07-10 15:26
**lurch: add

**Comment by LurchTheButler** [comment] 2017-07-10 15:30
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007I6hHAAS" target="_blank">W-019358</a>

**Comment by muchavie** [comment] 2017-09-20 17:32
Failed to reproduce this by hand following the recipe.

**Comment by jjbennett** [comment] 2017-09-29 22:26
@muchavie Thank you for taking a look, I just went through the steps again and I am still getting an error. Attaching a screen shot. Be sure to only have Contact A the only related contact to Household A and set Contact B as the Primary contact on Household A. Once that is set, then change the Contact Owner on Contact A.
![screen shot 2017-09-29 at 5 23 37 pm](https://user-images.githubusercontent.com/450473/31038253-446a3228-a53b-11e7-878d-8ca5eba1f8de.png)

**Comment by sanderott** [comment] 2019-09-10 13:01
Running into this same error, preventing us from operating owner updates on contacts after households are reassigned.

This bug occurs with following setup when attempting to update the owner of Contact 'A':
![NPSPOwnerBug](https://user-images.githubusercontent.com/11257110/64615995-e1bbf180-d3db-11e9-845d-f4c34b3ce32d.png)

'A Household' is linked to 'B' via `One2OneContact__c`, but also linked to 'A' (and only 'A') via Contacts related list. 
![relatedlist](https://user-images.githubusercontent.com/11257110/64615136-3eb6a800-d3da-11e9-9ede-bba2572f68b5.png)

-----
Bug occurs in `ACCT_IndividualAccounts_TDTM.updateOwners(...)`
Because there is only one related Contact, it will attempt to update `ownerId`, even if the contact that cause the trigger is a different contact than the One2OneContact on the Household.

Problem seems to lie in following lines
```Contact contactRecord = newOwnerContactById.get(accountRecord.npe01__One2OneContact__c);
Id ownerId = (contactRecord != null ? contactRecord.OwnerId : null);
if (accountRecord.OwnerId != ownerId) {
  accountRecord.OwnerId = ownerId;
  accountsToUpdate.put(accountRecord.Id, accountRecord);
}
```
If the `contactRecord` isn't found in the trigger context, it sets `ownerId` to null, which is a different owner than the `accountRecord`'s current OwnerId.

Suggestion: if the `if` statement checks if `ownerId` is null, it will no longer try to update the HH Accounts with empty OwnerId values.

**Comment by coriobriensfdo** [comment] 2019-09-10 18:48
Thanks for the additional comments and examples of the issue @sanderott! I've added a link to them on the internal work item for our PM's and developers to see.

**Comment by Elizabeth-Snow** [comment] 2020-01-24 18:13
I just ran into this as well.   Removing the primary contact from the one-to-one account then allowed me to update the owner of the wife of that account that was assigned to that account (before we had households).   Bad data management sometimes happens! 
![image](https://user-images.githubusercontent.com/60270381/73092737-647caf00-3e9a-11ea-9b42-2956bb5de7f9.png)

**Comment by jamesbsfdc** [comment] 2020-02-18 09:32
Another thread on this issue: https://powerofus.force.com/s/question/0D51E00005DXL7c/invalidcrossreferencekey-primary-account-owner-owner-cannot-be-blank-ownerid-npsp

**Comment by davidchengIC** [comment] 2021-06-15 00:21
This also occurs when using an Account record-triggered after-update Flow that updates household contacts to match the account owner if the account owner changes.

**Comment by mbeaty-sf** [comment] 2021-09-02 21:56
W-7783088

**Comment by kporray1** [comment] 2022-03-16 18:06
Please follow this [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000002dlFtQAI&title=changing-the-contact-owner-results-in-an-error-when-the-primary-contact-is-not-related-to-the-account) in the Trailblazer Community for updates.

**Closed by kporray1** 2022-03-16 18:06 UTC
Labels: bug, product_health
