### ISSUE TITLE
RD's Next Pledged Opportunity has Different Close Date depending on Last Opp's Close Date

### ISSUE THREAD

**Issue by jesslopez-sf** [SalesforceFoundation/NPSP#3126] opened 2018-05-08 13:22 UTC
If you modify a Recurring Donation's latest pledged Opportunity's Close Date, future pledged Opportunities will have different Close Dates, depending upon the day of the month. For example, if you change the latest Close Date to a date in the 28-31 range of the month, the next pledged Opportunity's Close Date will resume the normal Close Date pattern (i.e. if Opps were on the 8th of the month, it would resume using the 8th of the month). If, however, you change the last Close Date to a day prior to the 28th of the month, it changes the Close Date for the next pledged Opportunity to the day of the last Close Date (i.e. if you change it to the 27th, it would start the next Close Date at the 27th, rather than the 8th).

**Steps to Repeat (testing on 5/8/18, so it uses the 8th as the default):**
1. Set # of Forecast Months to 12 in NPSP Settings --> Recurring Donations. 
2. Create a Recurring Donation (Open Ended Status = 'Open', Installment Period = 'Monthly')
3. Verify that the Recurring Donation was created with 12 pledged Opportunities:

![original](https://user-images.githubusercontent.com/29731456/39759377-864fd05e-52a0-11e8-81a5-5a9d302abc7e.jpg)

4. Now, modify the latest Opportunity's Close Date. Change it from 4/8/2019 to 3/31/2019.
5. Click the **_Refresh Opportunities_** button on the Recurring Donation.
6. A new pledged Opportunity is created with a Close Date of 4/8/2019.
![31st close date](https://user-images.githubusercontent.com/29731456/39759502-d71f69b8-52a0-11e8-8d92-ab5c94b090ce.jpg)

7. Now delete the Opportunity that has a Close Date of 4/8/19.
8. Modify the last Opp's Close Date from 3/31/2019 to 3/27/19.
9. Click the **_Refresh Opportunities_** button on the Recurring Donation.
10. A new pledged Opportunity is created with a Close Date of 4/27/19.
![27th close date](https://user-images.githubusercontent.com/29731456/39759614-2456af2a-52a1-11e8-9706-de1c8b8548c6.jpg)

**Comment by LurchTheButler** [comment] 2018-05-08 13:25
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AWXr6AAH" target="_blank">W-024566</a>

**Comment by annacrotty** [comment] 2018-07-26 00:06
Apologies, I posted this on the wrong issue before.

Support suggested that behavior I'm seeing may be related to this.  To be clear:  what I'm seeing doesn't involve date changes.

I've got forecasting months set to 12.  Today is July 25th.  For all my yearly recurring donations that have processed already this month, they have zero open pledges.  For all my monthly recurring donations that have processed already this month, they  have eleven open pledges.  Based on previous experience, I *think* those open pledges will all appear on August 1st or 2nd.

Support and I can't tell if this is expected behavior or not.  It is unfortunate for us because our open pledge number varies widely depending on the time of the month - it looks like we're losing and gaining pledges when we're really not.  (Intuitively, people figure that if we're just retaining our existing recurring donors, that open pledge number stays constant.)  If it is expected, I'll stop worrying about it and just try to adjust reports to cover it up.  If it isn't expected, I'll continue to try to figure out what might be going wrong in our orgs.

**Comment by judisohn** [comment] 2018-07-26 00:11
@annacrotty Yes, it sounds like you're describing expected behavior. Forecast months isn't about how many open pledges, it's complete months ahead.

**Comment by mpusto** [comment] 2020-06-03 17:28
We are closing this issue because we will not be updating the old Recurring Donations functionality. We will be making all updates to our new Recurring Donations functionality. We recommend that customers evaluate the new features and upgrade when it makes sense for their organization. https://powerofus.force.com/s/article/NPSP-Enhanced-RD-Upgrade-Guide

**Closed by mpusto** 2020-06-03 17:28 UTC
