### ISSUE TITLE
Specify "Responded" with Custom Campaign Member Status in NPSP Import Tool

### ISSUE THREAD

**Issue by TracyKronzak** [SalesforceFoundation/NPSP#1996] opened 2016-03-18 15:54 UTC
Can we add the ability to specify whether or not a custom Campaign Member Status as created in the NPSP Data Loader also constitutes "Responded" for the overall Campaign it is either creating or attaching itself to?  This would save having to re-edit the Advanced Campaign Settings for Campaigns after the Import Tool Campaign Members have been created.  Thanks!

**Comment by judisohn** [comment] 2016-03-18 18:46
**lurch: add

**Comment by LurchTheButler** [comment] 2016-03-18 18:50
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003ON3gAAG" target="_blank">W-009667</a>

**Comment by mbeaty-sf** [comment] 2021-06-11 21:01
W-7781143

**Comment by jesslopez-sf** [comment] 2022-03-16 17:21
This is still open in our Backlog. As it's a feature request and not a bug, I won't be moving it into the Trailblazer Community Known Issues page.

**Closed by jesslopez-sf** 2022-03-16 17:21 UTC
Labels: accepted, product_health
