### ISSUE TITLE
Gift Entry Template "Add Section" Button is cut off from view with browser at normal zoom (100%)

### ISSUE THREAD

**Issue by jthall1** [SalesforceFoundation/NPSP#6943] opened 2022-04-22 16:07 UTC
When creating new templates in Gift Entry (or editing existing templates), if the template already has a number of fields in it, the "Add Section" button becomes obscured by the "Back: Template Info" // "Next: Batch Settings" overlay. It can be made visible again if you zoom WAY out in the browser but this is a not-very-intuitive workaround for most users (and might cause problems for users who need the text to be big enough to read).

Here's an example of a section where the "Add Section" button is obscured. In this screenshot, the window is scrolled all the way down.
![image](https://user-images.githubusercontent.com/25326187/164752514-b8cabe43-8ad6-4464-b703-6551f10af034.png)

Here's an example of how zoomed out you need to be in order to see the "Add Section" button again. In my browser this is 50% zoomed out:
![image](https://user-images.githubusercontent.com/25326187/164752706-e48357fc-102e-4b17-ba07-41456d80b166.png)

**Comment by mbeaty-sf** [comment] 2022-04-22 16:16
Hi ,

We don't provide support via GitHub Issues. In the future please post on the Trailblazer Community (https://trailhead.salesforce.com/trailblazer-community/) to have your question addressed by the community.

This issue in particular is a Known Issue, and you can follow it here. If you click "this issue affects me" then you will receive updates when the issue is updated: https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kRxQAI

Thank you

**Closed by mbeaty-sf** 2022-04-22 16:16 UTC
