### ISSUE TITLE
Opp Payment Field mappings limits source fields too much

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/NPSP#1934] opened 2016-02-09 19:05 UTC
We currently only allow custom fields from Opp, and the following standard/npsp fields:

'amount', 'closedate', 'expectedrevenue', 'probability', 'totalopportunityquantity', 'npe01__membership_start_date__c', 'npe01__membership_end_date__c'

should we just include all standard/npsp fields?  or specifically add to this list.

hub thread: https://powerofus.force.com/0D58000002UhKrj
user wanted to use the Opportunity Type field.

**Comment by davidhabib** [comment] 2016-02-09 19:06
**lurch: add

**Comment by LurchTheButler** [comment] 2016-02-09 19:10
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001qBkAAI" target="_blank">W-009307</a>

**Comment by judisohn** [comment] 2016-02-09 19:17
As it works to add them directly from Custom Settings, I don't think we necessarily have to add all the fields but I do think Opportunity Type might be a good one to consider.

**Comment by davidhabib** [comment] 2016-02-09 19:25
What is interesting to me, however, is why you would want to copy these fields to the payment, when the payment could just have a formula field getting the value from the Opp.

**Comment by judisohn** [comment] 2016-02-09 19:56
I'm guessing, but it's likely that as there's no Payment Type picklist (Check, Cash, Credit Card, etc) on Opportunity, an implementation repurposed the standard field for this. As Record Type defines the Type of Opportunity, and the Account's Record Type determines whether it's Household or Organization, the standard Opportunity Type field isn't heavily leveraged. Therefore, this would want to be updated for each payment rather than stay consistent across all payment records.

**Comment by johnfine** [comment] 2019-05-19 00:58
It would be nice if the error thrown on Opp creation when Opp.Type is mapped could be more specific than 'SObject row was retrieved via SOQL without querying the requested field: Opportunity.Payment__c'.  Took me an hour to isolate the cause.  (I didn't even really need Type mapped that much!).  Thx for considering.

**Comment by jamesbsfdc** [comment] 2021-01-15 10:50
[Another request for this](https://powerofus.force.com/s/question/0D51E00005XhcMoSAJ/npsp-settings-payment-mappings-the-opportunity-type-field-isnt-available)

**Comment by jamesbsfdc** [comment] 2021-01-15 15:43
Closing this issue as it is a feature limitation rather than a bug, and has a workaround. 

A request for the current behaviour to be changed van be logged via an Idea: https://trailblazer.salesforce.com/ideaSearch?filter=Nonprofit+%3E+Nonprofit+Success+Pack

**Closed** 2021-01-15 15:43 UTC
Labels: accepted
