### ISSUE TITLE
Find Matching Gifts page: provide diagnostic message(s) when search for matching opp fails

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/NPSP#1992] opened 2016-03-17 19:12 UTC
This exists today for the case when a user provides no search criteria in the Find More Gifts modal dialog: upon returning, the page shows "Warning:Please specify one or more filters in order to search."

But suppose that the user enters valid Account or Primary Contact or Amount or Close Date criteria that match at least one corresponding Opportunity record in the org. The user expects to find an Opportunity that matches, because the criteria they entered is valid and is connected to Opportunity records in the system.

When this query fails to return results, the page shows no diagnostic warning messages at all, it simply returns no records, and the user does not know why the search failed even with Opportunity records in the system that match their search criteria for Account, Primary Contact, etc.

**Comment by davidhabib** [comment] 2016-03-17 19:31
Chris, if there is truly a record that matches their criteria, it should be found by the soql query.  this isn't like search where the indexes get built in the background.  If you have a case where this happens, let's take a look.  I suspect you are incorrect (or else the query engine has a bug!).  That said, I would agree that if the find does not find any new opps, it would be nice to let the user know that.  But there is no system message to show, other than us saying "your criteria did not match any opportunities".

**Comment by chrismcmahon** [comment] 2016-03-17 19:35
"your criteria did not match any opportunities" would be a nice enhancement. Right now it's a silent failure.

**Comment by oagostinho** [comment] 2019-07-28 22:43
Hi

I would like to help with this. Any recommendation?  Thanks!

**Comment by coriobriensfdo** [comment] 2019-07-29 16:51
@oagostinho Great! What kind of recommendation are you looking for?

**Comment by oagostinho** [comment] 2019-07-29 17:14
Hi @oagostinho 

I saw the code...and it seems that I have to pop up one message to indicate that situation.

That situation has to be validated in the initial search when the form pops up and the following searches if that's the case.

In that way, is all of you need? I am just asking. ;.-)

Best Regards,
Orlando Agostinho

**Comment by coriobriensfdo** [comment] 2019-07-29 18:43
@oagostinho If you can, I'd recommend posting what you'd propose to build in the Power of Us Hub, in our [Open Source Contributors group](https://powerofus.force.com/s/group/0F980000000CtL2CAK/sfdo-open-source-contributors). That way you can get feedback on what you'd like to build, and we can get some of our team involved to review if needed before you dive into the code.

**Comment by oagostinho** [comment] 2019-07-30 11:51
HI @coriobriensfdo  

I don't have a user to log in in that group. I have a normal salesforce user from my company.

But, Anyway, I will do my best and let see what the people say....!

Thanks

**Comment by coriobriensfdo** [comment] 2019-07-30 15:57
@oagostinho have you worked with the Nonprofit Success Pack previously? The Hub is open to all who use the products through their Organization/Company (like an consultant or app partner), or as an NGO or Education institution. Do you fall in either of these categories?

**Comment by oagostinho** [comment] 2019-07-30 16:08
Hi

I am Salesforce Certified Profissional. 

My company in Portugal is an app partner. In a matter of fact, we are interested to work with Nonprofit Success Pack to help nonprofits organizations here in Portugal to use Salesforce NPSP for their activities.

At this moment, I am studying to do the certification exam for  NPSP. 

For all that, I am here learning more about this. ;-)

**Comment by coriobriensfdo** [comment] 2019-07-30 16:29
@oagostinho ah ok, thanks for the clarification. If you are looking to become a registered Salesforce.org partner you can learn more about that [here](https://www.salesforce.org/help/becomeapartner/form/). After you are approved you get access to the Power of Us Hub, so for now just tag me if you decide to contribute on the Issue and I can loop in folks to help with review.

**Comment by oagostinho** [comment] 2019-07-31 08:11
@coriobriensfdo Ok. I will.  Thanks

**Comment by oagostinho** [comment] 2019-08-04 10:20
Hi

@coriobriensfdo  I did the change - Adding the Warning message.  You can check it out the following PR (https://github.com/SalesforceFoundation/Cumulus/pull/4479)

Pardon me with the commit messages...I am still learning this git. ;-)

Cheers

P.S: One thing, I added a Custom Label for the warning message but It doesn't catch by CumulusCI. 

For that, I am including here:

mtchNotFindMoreGifts | Name | mtchNotFindMoreGifts
Language | English | Protected Component |  
Categories | Find Matched Gifts
Value | Your criteria did not match any opportunities

**Comment by judisohn** [comment] 2019-08-05 17:41
Thanks @oagostinho - @coriobriensfdo is out today but I'm sure she'll be in touch tomorrow. Thanks for your contribution. :-)

**Comment by coriobriensfdo** [comment] 2019-08-08 19:17
Great thank you @oagostinho! I'll add this to our backlog and get someone from the Engineering Team to take a look. :) We'll also follow up as we need to have you sign a CLA.

**Comment by coriobriensfdo** [comment] 2019-08-08 19:18
**Lurch: Add

**Comment by LurchTheButler** [comment] 2019-08-08 19:20
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C97iQAC" target="_blank">W-035179</a>

**Comment by coriobriensfdo** [comment] 2019-08-08 19:25
@oagostinho if you don't mind, can you send me an email with your contact details? I'm at cori.obrien@salesforce.com.

Thanks!

**Comment by oagostinho** [comment] 2019-08-09 08:20
Hi  @coriobriensfdo

I sent the mail..anything else, please let me know!

Cheers!

**Comment by jesslopez-sf** [comment] 2022-03-16 17:24
This is still open in our backlog. As this is a feature request and not a bug, I will not be moving it over to the Trailblazer Known Issues site.

**Closed by jesslopez-sf** 2022-03-16 17:24 UTC
Labels: enhancement, community-ready, product_health
