### ISSUE TITLE
Elevate: Clickjack protection blocks access to Salesforce.org Elevate in Gift Entry form

### ISSUE THREAD

**Issue by ptewson-sfdo** [SalesforceFoundation/NPSP#5724] opened 2020-08-07 18:30 UTC
**Issue**

When "Enable clickjack protection for customer Visualforce pages with headers disabled" is selected, the Credit Card fields for submitting payments to Elevate from the Gift Entry form will not load on the Gift Entry Form.

**Steps to Reproduce**

1. In session settings, click the checkbox next to "Enable clickjack protection for customer Visualforce pages with headers disabled" and save:

![image](https://user-images.githubusercontent.com/45107660/89676322-558ea480-d8a0-11ea-92fa-5b031af548aa.png)

2. On a Gift Form with the Salesforce.org Elevate bundle included, the credit card fields fail to load and display an infinite spinner:

![image](https://user-images.githubusercontent.com/45107660/89676716-f67d5f80-d8a0-11ea-9009-9e2efdd56df9.png)

**Workaround**

1. Remove the "Enable clickjack protection for customer Visualforce pages with headers disabled"  setting:

![image](https://user-images.githubusercontent.com/45107660/89676780-190f7880-d8a1-11ea-992d-7d284310f538.png)

2. Credit card fields load on Gift Entry form: 

![image](https://user-images.githubusercontent.com/45107660/89676940-5e33aa80-d8a1-11ea-9b18-baec13245eef.png)

**Comment by melissabarber** [comment] 2020-09-15 20:12
Closing this issue because clickjack is working as intended. Workaround for this limitation: https://powerofus.force.com/s/article/EL-Troubleshooting#ariaid-title2

**Closed by melissabarber** 2020-09-15 20:12 UTC
