### ISSUE TITLE
As a user, the "Always Rollup to Primary Contact Role" contact donations not attributed to the HH Account should have an option to roll up to HH accounts.

### ISSUE THREAD

**Issue by njjc** [SalesforceFoundation/NPSP#1455] opened 2015-03-12 23:41 UTC
[Per this hub thread.](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001wkkRA&emtm=1426195221664&s1nid=0DB800000004Fa7&OpenCommentForEdit=1&fromEmail=1&emkind=chatterCommentNotification&s1ext=0&s1oid=00D00000000hWLM&s1uid=00580000006ktn4)

**Comment by njjc** [comment] 2015-03-19 17:18
Tested in my dev org, with "Always Rollup to Primary Contact Role" the rollups still show up for the household accounts. Checking back with user that reported the issue.

**Comment by kbromer** [comment] 2015-10-09 15:43
**lurch: attach W-007238

**Comment by LurchTheButler** [comment] 2015-10-09 15:45
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001cXhAAI" target="_blank">W-007238</a>

**Comment by shawnholt** [comment] 2016-08-02 21:55
To be clear, if I have a primary contact donor on an opportunity linked to an org, this request will allow me to rollup to the contact household.  That implies that household donation total will always be the total of any opportunities with related household member contact roles.

**Comment by judisohn** [comment] 2016-08-03 10:22
Where the donor is marked as primary only. 

@mpusto This is very similar to #2149 but not identical (this one says it should be an option - other treats it as a regression). Which one should win? I think it's a regression since it automatically rolls up to Household object in One to One model, but not in Household Account model.

**Comment by mbeaty-sf** [comment] 2021-04-30 20:27
Closed as a duplicate Issue relating to this Issue has been closed.

**Closed by mbeaty-sf** 2021-04-30 20:27 UTC
Labels: accepted, product_health
