### ISSUE TITLE
Incorrect Recurring Donation summary on batch page when job fails due to limit error

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/NPSP#2441] opened 2017-01-05 15:05 UTC
I've been helping a customer who is consistently getting a SOQL error on the RD batch. In troubleshooting, I noticed that the information in the batch screen is misleading. It says that records were updated successfully, when they weren't (based on Last Modified Date on the RDs). 

![image](https://cloud.githubusercontent.com/assets/4614343/21685053/114ebfb0-d32e-11e6-8b56-4e7f31d7363e.png)

**Comment by judisohn** [comment] 2017-01-05 15:05
**lurch: add

**Comment by LurchTheButler** [comment] 2017-01-05 15:10
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004RBZVAA4" target="_blank">W-017376</a>

**Comment by njjc** [comment] 2017-01-11 19:39
The issue is that if an exception prevents the method from running, then the number of failures isn't returned to the controller.

Reminder to also fix possible infinite loops in the RD code by adding a max iterations counter.

**Comment by mpusto** [comment] 2020-06-03 17:19
We are closing this issue because we will not be updating the old Recurring Donations functionality. We will be making all updates to our new Recurring Donations functionality. We recommend that customers evaluate the new features and upgrade when it makes sense for their organization. https://powerofus.force.com/s/article/NPSP-Enhanced-RD-Upgrade-Guide

**Closed by mpusto** 2020-06-03 17:19 UTC
Labels: accepted
