### ISSUE TITLE
Account to account associations

### ISSUE THREAD

**Issue by mrbelvedere** [SalesforceFoundation/NPSP#1769] opened 2015-10-23 17:45 UTC
Hello from the Seattle NPSP sprint.

We are planning to work on account-to-account associations (paralleling contact-account relationships).

This will entail creating an Associated Account join object between account records for the purpose of tracking partnered organizations within the NPSP. Including the following fields:
- Account (master-detail)
- Associated Account (lookup w/ cascade delete)
- Association (picklist)
- Reciprocal Association (picklist)
- From Date
- To Date
- Description
- Status

Creating an Account Association will trigger the creation of a reciprocal Account Association in the other direction so that both outgoing and incoming associations can be viewed in a single related list. Deleting an Account Association will delete the reciprocal. Updating an Account Association will update the Association picklists, from/to date and status on the reciprocal.

**Comment by kbromer** [comment] 2015-10-23 17:55
If the 'Partner' object had From/To Date, Description, Status, would this solve the same problem?

**Comment by davisagli** [comment] 2015-10-27 07:12
Oops, didn't see @kbromer's question since @mrbelvedere didn't subscribe me to the issue it created for me. (/cc @jlantz, maybe it'd be sufficient to make it @-mention the creator's github handle?)

@BrightStepTracy can you answer Kevin's question or pull in someone who can? I'm not very familiar with the Partner object but I think you had an argument against using it.

**Comment by BrightStepTracy** [comment] 2015-10-27 14:35
@kbromer and @davisagli My objection to using the Partner Object is that for what nonprofits need, it's not what the Object is designed to do.  Similar to using the Owner field to designate relationship managers, and the Contact Role for donation crediting -- it feels structurally similar, but at the end of the day, it's not what Salesforce has designed the Object to handle.

The Partners related list is designed for team selling shared opportunities, and using it requires Account and Opportunity access for the Profile assigned to it (https://help.salesforce.com/HTViewHelpDoc?id=partners_edit.htm&language=en_US) -- nonprofits will take away Read access to Opportunities as part of separating out security between program/development departments.  Moreover, its status as an Object is not fully First Class, and it is too much designed for the management of Partner Communities from a security standpoint -- which means that for NPOs using these licenses, it will not scale.

The business process this is solving is when organizations want to collaborate in networks, see who is attached to what, and ultimately, provide a platform for visualization of Account-Account connections that can handle Organization and potentially Household record types (it was pointed out during the Sprint that many churches and faith-based institutions want to see Households in association with congregation, not just contacts).

Hope this helps!
T

**Comment by kbromer** [comment] 2015-10-27 16:51
So is there automation to this object? 

Playing devil's advocate here - why is this in the core package and not a custom object to be added for those organizations that need the increased functionality?

**Comment by davisagli** [comment] 2015-10-27 17:01
There is the same automation as for contact-contact relationships: When you add an association in one direction, an association in the reverse direction is added automatically (so that the associations can be seen from both sides in the same related list). And not all association types are symmetric, so it takes care of changing the association type to a reciprocal type (e.g. a "funder" association in one direction becomes a "grantee" association in the other) based on a custom setting.

Whether or not it should be in the core package probably depends on whether it's an 80% use case or not. From a technical standpoint it could go in a separate managed package, but then there's more work to migrate if it becomes clear that it should be in core later on.

**Comment by BrightStepTracy** [comment] 2015-11-02 18:14
Indeed, per @davisagli 's notes - This is really "Relationships" for Account records, and would be added to the NPSP with the same configurable structures.  It is currently something that is being done on inappropriate structures inside of Salesforce, and this is creating a means by which to standardize this process - both for organization-organization relationships, as well as more specific use cases such as church-household (account) relationships.

**Comment by mpusto** [comment] 2016-05-25 13:53
Please see PR for more details.

**Comment by mpusto** [comment] 2016-05-25 13:55
I am leaving this open because as I said in the PR, we could consider in the future with a potentially different architecture and significant demonstrated need from the community.

**Comment by backofficeteam** [comment] 2018-06-11 13:28
I have seen several postings about this and https://github.com/SalesforceFoundation/Cumulus/pull/1963 and the doc that @TracyKronzak created: https://docs.google.com/document/d/11e5I3m8Km8CB1b847tT3j7-xe5Hdnj7XHGvfFzBce9k/edit?pli=1 

We are looking for a best practice solution for associating accounts.  Has there been any progress or suggestions (other than partners) for the NPSP?

**Comment by judisohn** [comment] 2018-06-11 13:40
@backofficeteam Best place to have this conversation is in the Hub. We save Github conversations for only those things related to active development, of which this particular item is not currently scheduled. Thanks!

**Comment by mbeaty-sf** [comment] 2021-05-17 18:49
Salesforce has determined that this issue will not be explored further.

Please see linked PR for additional information and context regarding this feature request - https://github.com/SalesforceFoundation/NPSP/pull/1963

**Closed by mbeaty-sf** 2021-05-17 18:49 UTC
Labels: product_health
